// Generated by O/R mapper generator ver 1.0

#import <UIKit/UIKit.h>
#import "ORRecord.h"

@class ItemBase;

@interface ItemBase : ORRecord {
    NSDate* mDate;
    int mShelfId;
    int mServiceId;
    NSString* mIdString;
    NSString* mAsin;
    NSString* mName;
    NSString* mAuthor;
    NSString* mManufacturer;
    NSString* mCategory;
    NSString* mDetailURL;
    NSString* mPrice;
    NSString* mTags;
    NSString* mMemo;
    NSString* mImageURL;
    int mSorder;
    int mStar;
}

@property(nonatomic,retain) NSDate* date;
@property(nonatomic,assign) int shelfId;
@property(nonatomic,assign) int serviceId;
@property(nonatomic,retain) NSString* idString;
@property(nonatomic,retain) NSString* asin;
@property(nonatomic,retain) NSString* name;
@property(nonatomic,retain) NSString* author;
@property(nonatomic,retain) NSString* manufacturer;
@property(nonatomic,retain) NSString* category;
@property(nonatomic,retain) NSString* detailURL;
@property(nonatomic,retain) NSString* price;
@property(nonatomic,retain) NSString* tags;
@property(nonatomic,retain) NSString* memo;
@property(nonatomic,retain) NSString* imageURL;
@property(nonatomic,assign) int sorder;
@property(nonatomic,assign) int star;

+ (BOOL)migrate;

// CRUD (Create/Read/Update/Delete) operations

// Create/update operations
// Note: You should use 'save' method
- (void)_insert;
- (void)_update;

// Read operations (Finder)
+ (ItemBase *)find:(int)pid;
+ (ItemBase *)find_by_date:(NSDate*)key cond:(NSString*)cond;
+ (ItemBase *)find_by_date:(NSDate*)key;
+ (ItemBase *)find_by_itemState:(int)key cond:(NSString*)cond;
+ (ItemBase *)find_by_itemState:(int)key;
+ (ItemBase *)find_by_idType:(int)key cond:(NSString*)cond;
+ (ItemBase *)find_by_idType:(int)key;
+ (ItemBase *)find_by_idString:(NSString*)key cond:(NSString*)cond;
+ (ItemBase *)find_by_idString:(NSString*)key;
+ (ItemBase *)find_by_asin:(NSString*)key cond:(NSString*)cond;
+ (ItemBase *)find_by_asin:(NSString*)key;
+ (ItemBase *)find_by_name:(NSString*)key cond:(NSString*)cond;
+ (ItemBase *)find_by_name:(NSString*)key;
+ (ItemBase *)find_by_author:(NSString*)key cond:(NSString*)cond;
+ (ItemBase *)find_by_author:(NSString*)key;
+ (ItemBase *)find_by_manufacturer:(NSString*)key cond:(NSString*)cond;
+ (ItemBase *)find_by_manufacturer:(NSString*)key;
+ (ItemBase *)find_by_productGroup:(NSString*)key cond:(NSString*)cond;
+ (ItemBase *)find_by_productGroup:(NSString*)key;
+ (ItemBase *)find_by_detailURL:(NSString*)key cond:(NSString*)cond;
+ (ItemBase *)find_by_detailURL:(NSString*)key;
+ (ItemBase *)find_by_price:(NSString*)key cond:(NSString*)cond;
+ (ItemBase *)find_by_price:(NSString*)key;
+ (ItemBase *)find_by_tags:(NSString*)key cond:(NSString*)cond;
+ (ItemBase *)find_by_tags:(NSString*)key;
+ (ItemBase *)find_by_memo:(NSString*)key cond:(NSString*)cond;
+ (ItemBase *)find_by_memo:(NSString*)key;
+ (ItemBase *)find_by_imageURL:(NSString*)key cond:(NSString*)cond;
+ (ItemBase *)find_by_imageURL:(NSString*)key;
+ (ItemBase *)find_by_sorder:(int)key cond:(NSString*)cond;
+ (ItemBase *)find_by_sorder:(int)key;
+ (ItemBase *)find_by_star:(int)key cond:(NSString*)cond;
+ (ItemBase *)find_by_star:(int)key;

+ (NSMutableArray *)find_all:(NSString *)cond;

+ (dbstmt *)gen_stmt:(NSString *)cond;
+ (ItemBase *)find_first_stmt:(dbstmt *)stmt;
+ (NSMutableArray *)find_all_stmt:(dbstmt *)stmt;

// Delete operations
- (void)delete;
+ (void)delete_cond:(NSString *)cond;
+ (void)delete_all;

// internal functions
+ (NSString *)tableName;
- (void)_loadRow:(dbstmt *)stmt;

@end
