// Generated by O/R mapper generator ver 1.0

#import <UIKit/UIKit.h>
#import "ORRecord.h"

@interface ItemBase : ORRecord {
    NSString* mDate;
    int mShelfId;
    int mServiceId;
    NSString* mIdString;
    NSString* mAsin;
    NSString* mName;
    NSString* mAuthor;
    NSString* mManufacturer;
    NSString* mCategory;
    NSString* mDetailURL;
    NSString* mPrice;
    NSString* mTags;
    NSString* mMemo;
    NSString* mImageURL;
    int mSorder;
    int mStar;
}

@property(nonatomic,retain) NSString* date;
@property(nonatomic,assign) int shelfId;
@property(nonatomic,assign) int serviceId;
@property(nonatomic,retain) NSString* idString;
@property(nonatomic,retain) NSString* asin;
@property(nonatomic,retain) NSString* name;
@property(nonatomic,retain) NSString* author;
@property(nonatomic,retain) NSString* manufacturer;
@property(nonatomic,retain) NSString* category;
@property(nonatomic,retain) NSString* detailURL;
@property(nonatomic,retain) NSString* price;
@property(nonatomic,retain) NSString* tags;
@property(nonatomic,retain) NSString* memo;
@property(nonatomic,retain) NSString* imageURL;
@property(nonatomic,assign) int sorder;
@property(nonatomic,assign) int star;

+ (BOOL)migrate;

+ (id)allocator;

// CRUD (Create/Read/Update/Delete) operations

// Create/update operations
// Note: You should use 'save' method
- (void)_insert;
- (void)_update;

// Read operations
+ (ItemBase *)find:(int)pid;
+ (NSMutableArray *)find_cond:(NSString *)cond;
+ (dbstmt *)gen_stmt:(NSString *)cond;
+ (NSMutableArray *)find_stmt:(dbstmt *)cond;

// Delete operations
- (void)delete;
+ (void)delete_cond:(NSString *)cond;
+ (void)delete_all;

// internal functions
+ (NSString *)tableName;
- (void)_loadRow:(dbstmt *)stmt;

@end
