// Generated by O/R mapper generator ver 0.2

#import <UIKit/UIKit.h>
#import "ORRecord.h"

@interface ShelfBase : ORRecord {
    NSString* mName;
    int mSorder;
    int mShelfType;
    NSString* mTitleFilter;
    NSString* mAuthorFilter;
    NSString* mManufacturerFilter;
    NSString* mTagsFilter;
    int mStarFilter;
}

@property(nonatomic,retain) NSString* name;
@property(nonatomic,assign) int sorder;
@property(nonatomic,assign) int shelfType;
@property(nonatomic,retain) NSString* titleFilter;
@property(nonatomic,retain) NSString* authorFilter;
@property(nonatomic,retain) NSString* manufacturerFilter;
@property(nonatomic,retain) NSString* tagsFilter;
@property(nonatomic,assign) int starFilter;

+ (BOOL)migrate;

+ (id)allocator;

// CRUD (Create/Read/Update/Delete) operations

// Create/update operations
// Note: You should use 'save' method
- (void)_insert;
- (void)_update;

// Read operations
+ (ShelfBase *)find:(int)pid;
+ (NSMutableArray *)find_cond:(NSString *)cond;
+ (dbstmt *)gen_stmt:(NSString *)cond;
+ (NSMutableArray *)find_stmt:(dbstmt *)cond;

// Delete operations
- (void)delete;
+ (void)delete_cond:(NSString *)cond;
+ (void)delete_all;

// internal functions
+ (NSString *)tableName;
- (void)_loadRow:(dbstmt *)stmt;

@end
